version: "3"

networks:
  datalayer:
    driver: bridge

services:
  gql-lessons:
    container_name: gql-lessons
    build:
      context: "./servers/gql-lessons"
    env_file: ENVIRONMENT_VARS
    restart: always
    networks:
      - datalayer
    ports:
      - 4000:4000
