version: "3"

volumes:
  mongo-data:

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-data:/data/mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  # web-next:
  #   container_name: app-web
  #   build:
  #     context: ./packages/app-web
  #     dockerfile: Dockerfile.dev
  #   env_file:
  #     - ENVIRONMENT_VARS
  #   volumes:
  #     - ./packages/app-web/src/:/app/src
  #     - ./packages/app-web/public/:/app/public
  #     - ./packages/app-web/meta/:/app/meta
  #   restart: always
  #   ports:
  #     - 3000:3000
