version: "3"

networks:
  datalayer:
    driver: bridge

services:
  gql-configs:
    container_name: gql-configs
    build:
      context: "./servers/gql-configs"
    env_file: ENVIRONMENT_VARS
    restart: always
    networks:
      - datalayer
    ports:
      - 4000:4000

  # gateway:
  #   container_name: gateway
  #   build:
  #     context: "./servers/gateway"
  #   env_file: ENVIRONMENT_VARS
  #   restart: always
  #   depends_on:
  #     - gql-lessons
  #   networks:
  #     - datalayer
  #   ports:
  #     - 4000:4000
