export const UPDATE_FAST_NOTE = "UPDATE_FAST"
export const UPDATE_STABLE_NOTE = "UPDATE_STABLE"
export const TOGGLE_FRETLESS = "TOGGLE_FRETLESS"
export const TOGGLE_HAND_INDICATOR = "TOGGLE_HAND_INDICATOR"
