yarnPath: .yarn/releases/yarn-4.0.2.cjs
nodeLinker: "pnp"
packageExtensions:
  "@graphql-mesh/cli@^0.88.1":
    dependencies:
      "@types/node": "*"
      "graphql-tag": "*"
  "@graphql-mesh/config@^0.98.1":
    dependencies:
      "graphql-yoga": "^5.0.0"
  "@graphql-mesh/merger-bare@^0.96.0":
    dependencies:
      "@graphql-mesh/store": "^0.96.0"
      "@graphql-mesh/cross-helpers": "^0.4.1"
  "@graphql-mesh/graphql@^0.96.0":
    dependencies:
      "@graphql-mesh/cross-helpers": "*"
      "@graphql-mesh/store": "^0.96.0"
      "@graphql-mesh/types": "^0.96.0"
      "@graphql-mesh/utils": "^0.96.0"
      "@graphql-tools/utils": "^9.2.1"
      "tslib": "^2.4.0"
