import {
  Bbb,
  Ab,
  Bb,
  Cb,
  Db,
  Eb,
  Fb,
  Gb,
  An,
  Bn,
  Cn,
  Dn,
  En,
  Fn,
  Gn,
  As,
  Bs,
  Cs,
  Ds,
  Es,
  Fs,
  Gs,
  Ass,
  Css,
  Dss,
  Fss,
  Gss,
} from "./note-names"

// Proper names for the circle stations for given number of sharps or flats:
export default {
  [+7]: [Bs, Gn, Dn, An, En, Bn, Fs, Cs, Gs, Ds, As, Es],
  [+6]: [Cn, Gn, Dn, An, En, Bn, Fs, Cs, Gs, Ds, As, Es],
  [+5]: [Cn, Gn, Dn, An, En, Bn, Fs, Cs, Gs, Ds, As, Fn],
  [+4]: [Cn, Gn, Dn, An, En, Bn, Fs, Cs, Gs, Ds, As, Fn],
  [+3]: [Cn, Gn, Dn, An, En, Bn, Fs, Cs, Gs, Ds, As, Fn],
  [+2]: [Cn, Gn, Dn, An, En, Bn, Fs, Cs, Gs, Ds, As, Fn],
  [+1]: [Cn, Gn, Dn, An, En, Bn, Fs, Cs, Gs, Ds, As, Fn],
  [0]: [Cn, Gn, Dn, An, En, Bn, Fs, Cs, Gs, Ds, As, Fn], // Could be sharps or flats
  [-1]: [Cn, Gn, Dn, An, En, Bn, Gb, Db, Ab, Eb, Bb, Fn],
  [-2]: [Cn, Gn, Dn, An, En, Bn, Gb, Db, Ab, Eb, Bb, Fn],
  [-3]: [Cn, Gn, Dn, An, En, Bn, Gb, Db, Ab, Eb, Bb, Fn],
  [-4]: [Cn, Gn, Dn, An, En, Bn, Gb, Db, Ab, Eb, Bb, Fn],
  [-5]: [Cn, Gn, Dn, An, En, Bn, Gb, Db, Ab, Eb, Bb, Fn],
  [-6]: [Cn, Gn, Dn, An, En, Cb, Gb, Db, Ab, Eb, Bb, Fn],
  [-7]: [Cn, Gn, Dn, An, Fb, Cb, Gb, Db, Ab, Eb, Bb, Fn],
}
