import BodyWrapper from "./body-wrapper.c";

import StyledComponentsRegistry from "../state/styles-registry";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <BodyWrapper>
        <body>
          <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
        </body>
      </BodyWrapper>
    </html>
  );
}
