import BodyWrapper from "./body-wrapper.c";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <BodyWrapper>
        <body>{children}</body>
      </BodyWrapper>
    </html>
  );
}
